using UnityEngine;
using System.Collections;

public class DamageCardDatabase : DamageCard {

	// Use this for initialization
	void Start () {
		GameObject cardGO;
		DamageCard card;

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Pathetic Swing";
		card.CardDescription = "The weakest of them all";
		card.CardCost = 1;
		card.Range = 1;
		card.Area = 0;
		card.Mobility = false;
		card.Effect = Effects.Empty;
		card.Rarity = Raritys.Starter;
		card.RequiredClass = RequiredClasses.Any;
		card.CardDamage = 1;
		card.DamageType = DamageTypes.Physical;
		card.Target = Targets.Enemy;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Backstab";
		card.CardDescription = "Cowards move";
		card.CardCost = 2;
		card.Range = 1;
		card.Area = 0;
		card.Mobility = false;
		card.Effect = Effects.Bleed;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Rogue;
		card.CardDamage = 3;
		card.DamageType = DamageTypes.Physical;
		card.Target = Targets.Enemy;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Ignite";
		card.CardDescription = "Ignite";
		card.CardCost = 1;
		card.Range = 6;
		card.Area = 0;
		card.Mobility = false;
		card.Effect = Effects.Burn;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Mage;
		card.CardDamage = 1;
		card.DamageType = DamageTypes.Magic;
		card.Target = Targets.Enemy;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Leap Slam";
		card.CardDescription = "Leap Slam";
		card.CardCost = 3;
		card.Range = 5;
		card.Area = 1;
		card.Mobility = true;
		card.Effect = Effects.Empty;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Warrior;
		card.CardDamage = 2;
		card.DamageType = DamageTypes.Physical;
		card.Target = Targets.AreaMobility;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Punch";
		card.CardDescription = "Punch";
		card.CardCost = 1;
		card.Range = 1;
		card.Area = 0;
		card.Mobility = false;
		card.Effect = Effects.Empty;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Any;
		card.CardDamage = 2;
		card.DamageType = DamageTypes.Physical;
		card.Target = Targets.Enemy;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Shield Bash";
		card.CardDescription = "Shield Bash";
		card.CardCost = 2;
		card.Range = 1;
		card.Area = 0;
		card.Mobility = false;
		card.Effect = Effects.Stun;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Warrior;
		card.CardDamage = 2;
		card.DamageType = DamageTypes.Physical;
		card.Target = Targets.Enemy;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Stun Arrow";
		card.CardDescription = "Stun Arrow";
		card.CardCost = 2;
		card.Range = 10;
		card.Area = 0;
		card.Mobility = false;
		card.Effect = Effects.Stun;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Rogue;
		card.CardDamage = 1;
		card.DamageType = DamageTypes.Ranged;
		card.Target = Targets.Line;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Fire Fist";
		card.CardDescription = "Fire Fist";
		card.CardCost = 3;
		card.Range = 1;
		card.Area = 0;
		card.Mobility = false;
		card.Effect = Effects.Burn;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Warrior;
		card.CardDamage = 3;
		card.DamageType = DamageTypes.Magic;
		card.Target = Targets.Enemy;
		GameController.control.AddDamageCardToDatabase(card);;

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Blizzard";
		card.CardDescription = "Blizzard";
		card.CardCost = 3;
		card.Range = 6;
		card.Area = 2;
		card.Mobility = false;
		card.Effect = Effects.Chill;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Mage;
		card.CardDamage = 1;
		card.DamageType = DamageTypes.Magic;
		card.Target = Targets.Area;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Poison Arrow";
		card.CardDescription = "Poison Arrow";
		card.CardCost = 2;
		card.Range = 10;
		card.Area = 0;
		card.Mobility = false;
		card.Effect = Effects.Poison;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Rogue;
		card.CardDamage = 1;
		card.DamageType = DamageTypes.Ranged;
		card.Target = Targets.Line;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Bear Trap";
		card.CardDescription = "Bear Trap";
		card.CardCost = 1;
		card.Range = 1;
		card.Area = 0;
		card.Mobility = false;
		card.Effect = Effects.Stun;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Rogue;
		card.CardDamage = 4;
		card.DamageType = DamageTypes.Physical;
		card.Target = Targets.Trap;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Poison Cloud Arrow";
		card.CardDescription = "Poison Cloud Arrow";
		card.CardCost = 3;
		card.Range = 10;
		card.Area = 1;
		card.Mobility = false;
		card.Effect = Effects.Poison;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Rogue;
		card.CardDamage = 1;
		card.DamageType = DamageTypes.Ranged;
		card.Target = Targets.Line;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Fireball";
		card.CardDescription = "Fireball";
		card.CardCost = 3;
		card.Range = 8;
		card.Area = 1;
		card.Mobility = false;
		card.Effect = Effects.Burn;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Mage;
		card.CardDamage = 3;
		card.DamageType = DamageTypes.Magic;
		card.Target = Targets.Line;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Shadow Strike";
		card.CardDescription = "Shadow Strike";
		card.CardCost = 2;
		card.Range = 4;
		card.Area = 0;
		card.Mobility = true;
		card.Effect = Effects.Bleed;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Rogue;
		card.CardDamage = 2;
		card.DamageType = DamageTypes.Physical;
		card.Target = Targets.Enemy;
		GameController.control.AddDamageCardToDatabase(card);

		cardGO = (GameObject)Instantiate(cardPrefab);
		card = cardGO.GetComponent<DamageCard>();
		card.CardName = "Flame Breath";
		card.CardDescription = "Flame Breath";
		card.CardCost = 2;
		card.Range = 3;
		card.Area = 0;
		card.Mobility = false;
		card.Effect = Effects.Burn;
		card.Rarity = Raritys.Basic;
		card.RequiredClass = RequiredClasses.Mage;
		card.CardDamage = 2;
		card.DamageType = DamageTypes.Magic;
		card.Target = Targets.Cone;
		GameController.control.AddDamageCardToDatabase(card);
	}
}
